# Generated by Django 5.2.4 on 2025-07-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRM_ID', models.IntegerField()),
                ('Select_your_role', models.CharField(choices=[('student', 'Student'), ('sponsor', "Student's Sponsor")], max_length=100)),
                ('Are_you_currently_employed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=100)),
                ('Select_your_Employment_Status', models.CharField(choices=[('permanant', 'Permanant'), ('goverment', 'Goverment'), ('fixed-term', 'Fixed-Term'), ('temporary', 'Temporary'), ('independant consultant', 'Independant Consultant'), ('pensioner', 'Pensioner'), ('selft-employed', 'Self-EMployed')], max_length=100)),
                ('Gross_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Net_Income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Additional_Income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tuition_fee_to_be_funded', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Course_Name', models.CharField(choices=[('diploma in Full stack Development', 'Diploma in Full-Stack development'), ('diploma in Data Science', 'Diploma in Data Science')], max_length=100)),
                ('Select_the_total_course_duration', models.CharField(choices=[('1 Month', '1 MOnth'), ('2 months', '2 Months'), ('3 months', '3 Months'), ('5 months', '5 Months'), ('6 months', '6 Months'), ('8 months', '8 Months'), ('9 months', '9 Months'), ('1 year', '1Year'), ('2 years', '2 Years'), ('3 years', '3 Years'), ('4 years', '4 Years'), ('5 years', '5 Years')], max_length=100)),
                ('Your_Name', models.CharField(max_length=50)),
                ('Your_Surname', models.CharField(max_length=50)),
                ('Your_ID_type', models.CharField(choices=[('south african identity number', 'SOuth African Identity Number'), ('passport or permit number', 'Passport or Permit Number')], max_length=150)),
                ('Your_ID_Number', models.IntegerField()),
                ('Your_Alternate_contact_number', models.BigIntegerField()),
                ('Your_Parent_Contact_number', models.BigIntegerField()),
                ('Your_Email_Address', models.EmailField(max_length=254)),
                ('Your_Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100)),
                ('Your_Province', models.CharField(choices=[('gauteng', 'Gauteng'), ('western cape', 'Western Cape'), ('kwazulu-natl', 'KwaZulu-Natal'), ('eastern cape', 'Eastern Cape'), ('free state', 'Free State'), ('limpopo', 'Limpopo'), ('mpumalanga', 'Mpumalanga'), ('northen cape', ' Northen Cape'), ('north west', 'North West')], max_length=100)),
                ('Your_Address_with_Zip_Code', models.CharField(max_length=250)),
                ('Upload_your_Address_proof', models.FileField(upload_to='documents/')),
                ('Upload_your_ID_Proof', models.FileField(upload_to='documets/')),
                ('Upload_your_last_3_months_pay_slip', models.FileField(upload_to='documents/')),
                ('Upload_your_last_3_months_bank_statement', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
