# Generated by Django 5.2.4 on 2025-07-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Upload_your_Address_proof',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Upload_your_ID_Proof',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Upload_your_last_3_months_bank_statement',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Upload_your_last_3_months_pay_slip',
        ),
        migrations.AlterField(
            model_name='application',
            name='CRM_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Your_ID_type',
            field=models.CharField(choices=[('south african identity number', 'South African Identity Number'), ('passport or permit number', 'Passport or Permit Number')], max_length=150),
        ),
    ]
