# Generated by Django 5.2.4 on 2025-07-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_form', '0002_remove_application_upload_your_address_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Course_Name',
            field=models.CharField(choices=[('diploma in Full stack Development', 'Diploma in Full-Stack development'), ('diploma in Data Science', 'Diploma in Data Science'), ('cyber security', 'Cyber Security'), ('ui/ux design', 'UI/UX Design')], max_length=100),
        ),
    ]
