# Generated by Django 5.2.4 on 2025-07-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_form', '0003_alter_application_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Course_Name',
            field=models.CharField(choices=[('diploma in Full stack Development', 'Diploma in Full-Stack development'), ('diploma in Data Science', 'Diploma in Data Science'), ('cyber security', 'Diploma in Cyber Security'), ('ui/ux design', 'Diploma in UI/UX Design')], max_length=100),
        ),
    ]
