# Generated by Django 5.2.4 on 2025-08-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_form', '0004_alter_application_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Your_ID_Number',
            field=models.BigIntegerField(),
        ),
    ]
