# Generated by Django 5.2.4 on 2025-08-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_form', '0005_alter_application_your_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Additional_Income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='Gross_income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='Net_Income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='Tuition_fee_to_be_funded',
            field=models.IntegerField(),
        ),
    ]
